"""Add autoincrement to telemetry id column

Revision ID: 861e7d9a056d
Revises: c271e05ca989
Create Date: 2025-10-24 18:25:58.130958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861e7d9a056d'
down_revision: Union[str, None] = 'c271e05ca989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('telemetry_timestamp_idx', table_name='telemetry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('telemetry_timestamp_idx', 'telemetry', [sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
