"""Initial migration

Revision ID: 9912eb070844
Revises: 
Create Date: 2025-10-24 16:36:48.221864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9912eb070844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('min_elevation', sa.Float(), nullable=True),
    sa.Column('max_range_km', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_ground_stations_id'), 'ground_stations', ['id'], unique=False)
    op.create_index(op.f('ix_ground_stations_name'), 'ground_stations', ['name'], unique=True)
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tle_line1', sa.Text(), nullable=False),
    sa.Column('tle_line2', sa.Text(), nullable=False),
    sa.Column('tle_epoch', sa.DateTime(), nullable=True),
    sa.Column('satellite_group', sa.String(length=100), nullable=True),
    sa.Column('satellite_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellites_id'), 'satellites', ['id'], unique=False)
    op.create_index(op.f('ix_satellites_name'), 'satellites', ['name'], unique=False)
    op.create_index(op.f('ix_satellites_norad_id'), 'satellites', ['norad_id'], unique=True)
    op.create_index(op.f('ix_satellites_satellite_group'), 'satellites', ['satellite_group'], unique=False)
    op.create_table('satellite_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('ground_station_id', sa.Integer(), nullable=False),
    sa.Column('rise_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('set_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_elevation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_elevation', sa.Float(), nullable=False),
    sa.Column('rise_azimuth', sa.Float(), nullable=False),
    sa.Column('set_azimuth', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ground_station_id'], ['ground_stations.id'], ),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_passes_rise_time', 'satellite_passes', ['rise_time'], unique=False)
    op.create_index('idx_passes_sat_station', 'satellite_passes', ['satellite_id', 'ground_station_id'], unique=False)
    op.create_index(op.f('ix_satellite_passes_ground_station_id'), 'satellite_passes', ['ground_station_id'], unique=False)
    op.create_index(op.f('ix_satellite_passes_id'), 'satellite_passes', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_passes_satellite_id'), 'satellite_passes', ['satellite_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('velocity_x', sa.Float(), nullable=False),
    sa.Column('velocity_y', sa.Float(), nullable=False),
    sa.Column('velocity_z', sa.Float(), nullable=False),
    sa.Column('altitude_km', sa.Float(), nullable=True),
    sa.Column('velocity_km_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_sat_time', 'telemetry', ['satellite_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_satellite_id'), 'telemetry', ['satellite_id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_satellite_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_index('idx_telemetry_sat_time', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_satellite_passes_satellite_id'), table_name='satellite_passes')
    op.drop_index(op.f('ix_satellite_passes_id'), table_name='satellite_passes')
    op.drop_index(op.f('ix_satellite_passes_ground_station_id'), table_name='satellite_passes')
    op.drop_index('idx_passes_sat_station', table_name='satellite_passes')
    op.drop_index('idx_passes_rise_time', table_name='satellite_passes')
    op.drop_table('satellite_passes')
    op.drop_index(op.f('ix_satellites_satellite_group'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_norad_id'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_name'), table_name='satellites')
    op.drop_index(op.f('ix_satellites_id'), table_name='satellites')
    op.drop_table('satellites')
    op.drop_index(op.f('ix_ground_stations_name'), table_name='ground_stations')
    op.drop_index(op.f('ix_ground_stations_id'), table_name='ground_stations')
    op.drop_table('ground_stations')
    # ### end Alembic commands ###
