"""Refactor telemetry to single primary key for TimescaleDB compatibility

Revision ID: e2d4cce36960
Revises: 861e7d9a056d
Create Date: 2025-10-24 21:00:02.355683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d4cce36960'
down_revision: Union[str, None] = '861e7d9a056d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_telemetry_satellite_id'), 'telemetry', ['satellite_id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_satellite_timestamp', 'telemetry', ['satellite_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_satellite_timestamp', 'telemetry', type_='unique')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_satellite_id'), table_name='telemetry')
    # ### end Alembic commands ###
